#!/usr/bin/env python3
from PIL import Image
import os

ROOT = os.path.join(os.path.dirname(__file__), '..')
PIC_DIR = os.path.join(ROOT, 'pic', 'menu_covers')
SRC = os.path.join(PIC_DIR, 'menu_cover_options_3x3.png')
OUT = os.path.join(ROOT, 'include', 'menu_covers.h')

COVER_W = 88
COVER_H = 88
COVERS = [
    ('dino_cover_a.png', 'dino', 0),
    ('2048_cover_a.png', 'game2048', 1),
    ('snake_cover_a.png', 'snake', 2),
]


def rgb565(pixel):
    r, g, b = pixel[:3]
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def sanitize(name):
    return ''.join(c if c.isalnum() else '_' for c in name).strip('_')


def main():
    os.makedirs(PIC_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)

    sheet = Image.open(SRC).convert('RGB')
    cell_w = sheet.width // 3
    cell_h = sheet.height // 3

    entries = []
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by tools/menu_covers_to_header.py\n')
        f.write('#pragma once\n#include <stdint.h>\n\n')
        f.write('typedef struct {\n')
        f.write('  const char* name;\n')
        f.write('  uint16_t w;\n')
        f.write('  uint16_t h;\n')
        f.write('  const uint16_t* pixels;\n')
        f.write('} MenuCover;\n\n')

        for filename, key, row in COVERS:
            crop = sheet.crop((0, row * cell_h, cell_w, (row + 1) * cell_h))
            cover = crop.resize((COVER_W, COVER_H), Image.Resampling.LANCZOS)
            cover_path = os.path.join(PIC_DIR, filename)
            cover.save(cover_path)

            pixels = [rgb565(cover.getpixel((x, y))) for y in range(COVER_H)
                      for x in range(COVER_W)]
            array_name = 'cover_' + sanitize(key)
            f.write('static const uint16_t %s[] = {\n  ' % array_name)
            for i, value in enumerate(pixels):
                f.write('0x%04X' % value)
                if i != len(pixels) - 1:
                    f.write(',')
                if (i + 1) % 12 == 0 and i != len(pixels) - 1:
                    f.write('\n  ')
            f.write('\n};\n\n')
            entries.append((key, array_name))

        f.write('static const MenuCover kMenuCovers[] = {\n')
        for key, array_name in entries:
            f.write('  {"%s", %d, %d, %s},\n' %
                    (key, COVER_W, COVER_H, array_name))
        f.write('};\n\n')
        f.write('static constexpr uint16_t kMenuCoversCount = %d;\n' %
                len(entries))

    print('Wrote', OUT)
    for filename, _, _ in COVERS:
        print('Wrote', os.path.join(PIC_DIR, filename))


if __name__ == '__main__':
    main()
