#!/usr/bin/env python3
from PIL import Image
import os

ROOT = os.path.join(os.path.dirname(__file__), '..')
PIC_DIR = os.path.join(ROOT, 'pic')
OUT = os.path.join(ROOT, 'include', 'game_sprites.h')

# Keep order stable for deterministic output.
SPRITE_FILES = [
    'bird_01.png', 'bird_02.png',
    'cactus_01.png', 'cactus_02.png', 'cactus_03.png', 'cactus_04.png',
    'cloud.png',
    'dino_01.png', 'dino_02.png', 'dino_03.png', 'dino_04.png', 'dino_05.png', 'dino_06.png',
    'ground.png',
    'game_over.png', 'restart.png',
    'char_H.png', 'char_I.png',
    'number_0.png', 'number_1.png', 'number_2.png', 'number_3.png', 'number_4.png',
    'number_5.png', 'number_6.png', 'number_7.png', 'number_8.png', 'number_9.png',
]

# These sprites look better as outlines than as filled silhouettes.
OUTLINE_SPRITES = {
    'bird_01.png', 'bird_02.png',
    'cactus_01.png', 'cactus_02.png', 'cactus_03.png', 'cactus_04.png',
    'dino_01.png', 'dino_02.png', 'dino_03.png', 'dino_04.png', 'dino_05.png', 'dino_06.png',
}


def sanitize(name: str) -> str:
    out = []
    for c in name.lower():
        if c.isalnum():
            out.append(c)
        else:
            out.append('_')
    s = ''.join(out)
    while '__' in s:
        s = s.replace('__', '_')
    return s.strip('_')


def pack_mono_bits(path: str, outline_only: bool = False):
    img = Image.open(path).convert('RGBA')
    w, h = img.size
    px = img.load()
    row_bytes = (w + 7) // 8

    def is_foreground(x: int, y: int) -> bool:
        r, g, b, a = px[x, y]
        luminance = (r * 299 + g * 587 + b * 114) // 1000
        return a >= 16 and luminance < 240

    data = []
    for y in range(h):
        for b in range(row_bytes):
            v = 0
            for i in range(8):
                x = b * 8 + i
                bit = 0
                if x < w and is_foreground(x, y):
                    if outline_only:
                        left_bg = x == 0 or not is_foreground(x - 1, y)
                        right_bg = x == w - 1 or not is_foreground(x + 1, y)
                        up_bg = y == 0 or not is_foreground(x, y - 1)
                        down_bg = y == h - 1 or not is_foreground(x, y + 1)
                        if left_bg or right_bg or up_bg or down_bg:
                            bit = 1
                    else:
                        bit = 1
                v = (v << 1) | bit
            data.append(v)
    return w, h, row_bytes, data


os.makedirs(os.path.dirname(OUT), exist_ok=True)
entries = []

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by tools/pngs_to_header.py\n')
    f.write('#pragma once\n#include <stdint.h>\n\n')
    f.write('typedef struct {\n')
    f.write('  const char* name;\n')
    f.write('  uint16_t w;\n')
    f.write('  uint16_t h;\n')
    f.write('  uint16_t row_bytes;\n')
    f.write('  const uint8_t* data;\n')
    f.write('} GameSprite;\n\n')

    for name in SPRITE_FILES:
        p = os.path.join(PIC_DIR, name)
        if not os.path.exists(p):
            print('WARN missing', name)
            continue
        w, h, rowb, data = pack_mono_bits(p, name in OUTLINE_SPRITES)
        key = sanitize(name)
        f.write('static const uint8_t sprite_%s[] = {\n  ' % key)
        for i, b in enumerate(data):
            f.write(str(b))
            if i != len(data) - 1:
                f.write(',')
            if (i + 1) % 24 == 0 and i != len(data) - 1:
                f.write('\n  ')
        f.write('\n};\n\n')
        entries.append((name, key, w, h, rowb))

    f.write('static const GameSprite kGameSprites[] = {\n')
    for name, key, w, h, rowb in entries:
        f.write('  {"%s", %d, %d, %d, sprite_%s},\n' % (name, w, h, rowb, key))
    f.write('};\n\n')
    f.write('static const uint16_t kGameSpritesCount = %d;\n\n' % len(entries))
    f.write('inline const GameSprite* FindGameSpriteByName(const char* name) {\n')
    f.write('  if (name == nullptr) return nullptr;\n')
    f.write('  for (uint16_t i = 0; i < kGameSpritesCount; ++i) {\n')
    f.write('    const char* s = kGameSprites[i].name;\n')
    f.write('    uint16_t j = 0;\n')
    f.write('    for (;; ++j) {\n')
    f.write('      if (s[j] != name[j]) break;\n')
    f.write('      if (s[j] == 0) return &kGameSprites[i];\n')
    f.write('    }\n')
    f.write('  }\n')
    f.write('  return nullptr;\n')
    f.write('}\n')

print('Wrote', OUT)
print('count=', len(entries))
